env:
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: true
  no-underscore-dangle:
    - error
    - allow: [_id]
      allowAfterThis: true
      allowAfterSuper: true
  max-classes-per-file: off
  no-param-reassign: off
