version: "3.7"

services:
  mongo:
    image: mongo:4.2-bionic
    tmpfs: /data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet
      interval: 30s
      timeout: 5s
      retries: 3
    hostname: mongo
    ports:
      - 27017:27017
